version: '3.1'

services:
  top-items:
      image: top-items:latest
      container_name: top-items
      restart: always
      ports:
        - 3000:3000
      volumes:
        - ./.env:/opt/app/.env

  top_items:
    image: mongo
    restart: 'no'
    volumes:
      - ".docker/mongo-db/init/init-db.js:/docker-entrypoint-initdb.d/init.js:ro"
      - ".docker/mongo-db/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'top_app_root'
      MONGO_INITDB_ROOT_PASSWORD: 'top_app_root_pass'
      MONGODB_USER: 'top_items_app'
      MONGODB_DATABASE: 'top_items_app_db'
      MONGODB_PASS: 'top_items_app_password'
    ports:
      - 27017:27017
    env_file:
      - '.env'

  mongo-express:
    image: mongo-express
    restart: 'no'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'top_app_root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'top_app_root_pass'
      ME_CONFIG_MONGODB_SERVER: top_items
